In [69]:
import pandas as pd
import numpy as np

data = "C:/Users/ABDULRASHID/Downloads/Total Emissions Per Country (2000-2020).csv"
df = pd.read_csv(data)
df

,Area,Item,Element,Unit,2000,2001,2002,2003,2004,2005,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Afghanistan,Crop Residues,Direct emissions (N2O),kilotonnes,5.200000e-01,5.267000e-01,8.200000e-01,9.988000e-01,8.225000e-01,1.182100e+00,...,1.032100e+00,1.372600e+00,1.401800e+00,1.458400e+00,1.242400e+00,1.194000e+00,1.061700e+00,8.988000e-01,1.217600e+00,1.317000e+00
1,Afghanistan,Crop Residues,Indirect emissions (N2O),kilotonnes,1.170000e-01,1.185000e-01,1.845000e-01,2.247000e-01,1.851000e-01,2.660000e-01,...,2.322000e-01,3.088000e-01,3.154000e-01,3.281000e-01,2.795000e-01,2.687000e-01,2.389000e-01,2.022000e-01,2.740000e-01,2.963000e-01
2,Afghanistan,Crop Residues,Emissions (N2O),kilotonnes,6.370000e-01,6.452000e-01,1.004500e+00,1.223500e+00,1.007500e+00,1.448100e+00,...,1.264300e+00,1.681500e+00,1.717300e+00,1.786500e+00,1.522000e+00,1.462700e+00,1.300500e+00,1.101100e+00,1.491600e+00,1.613300e+00
3,Afghanistan,Crop Residues,Emissions (CO2eq) from N2O (AR5),kilotonnes,1.688070e+02,1.709884e+02,2.661975e+02,3.242195e+02,2.669995e+02,3.837498e+02,...,3.350379e+02,4.455958e+02,4.550727e+02,4.734174e+02,4.033181e+02,3.876130e+02,3.446447e+02,2.917838e+02,3.952689e+02,4.275284e+02
4,Afghanistan,Crop Residues,Emissions (CO2eq) (AR5),kilotonnes,1.688070e+02,1.709884e+02,2.661975e+02,3.242195e+02,2.669995e+02,3.837498e+02,...,3.350379e+02,4.455958e+02,4.550727e+02,4.734174e+02,4.033181e+02,3.876130e+02,3.446447e+02,2.917838e+02,3.952689e+02,4.275284e+02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58760,OECD,All sectors without LULUCF,Emissions (CO2),kilotonnes,1.334328e+07,1.326305e+07,1.332979e+07,1.352237e+07,1.366651e+07,1.369481e+07,...,1.289801e+07,1.270146e+07,1.274243e+07,1.261664e+07,1.253301e+07,1.241227e+07,1.243658e+07,1.254684e+07,1.217070e+07,1.088919e+07
58761,OECD,All sectors without LULUCF,Emissions (CO2eq) from F-gases (AR5),kilotonnes,3.941893e+05,3.882647e+05,4.176531e+05,4.392191e+05,4.672796e+05,5.080909e+05,...,7.759070e+05,7.826597e+05,8.006688e+05,8.326775e+05,8.546258e+05,8.741566e+05,8.884415e+05,9.049044e+05,9.172806e+05,9.208261e+05
58762,OECD,All sectors without LULUCF,Emissions (CO2eq) from CH4 (AR5),kilotonnes,2.145052e+06,2.126567e+06,2.093083e+06,2.038232e+06,2.047953e+06,2.008645e+06,...,1.980459e+06,1.971959e+06,1.922551e+06,1.934854e+06,1.924370e+06,1.880327e+06,1.915982e+06,1.923635e+06,1.882769e+06,1.825476e+06
58763,OECD,All sectors without LULUCF,Emissions (CO2eq) from N2O (AR5),kilotonnes,8.535273e+05,8.496131e+05,8.400758e+05,8.124412e+05,8.328157e+05,8.123489e+05,...,8.344119e+05,8.490201e+05,8.204159e+05,8.325680e+05,8.289014e+05,8.218071e+05,8.400423e+05,8.349622e+05,8.118189e+05,8.009744e+05
58764,OECD,All sectors without LULUCF,Emissions (CO2eq) (AR5),kilotonnes,1.673605e+07,1.662750e+07,1.668060e+07,1.681226e+07,1.701456e+07,1.702390e+07,...,1.648879e+07,1.630510e+07,1.628606e+07,1.621674e+07,1.614090e+07,1.598856e+07,1.608104e+07,1.621034e+07,1.578256e+07,1.443647e+07

In [70]:
df.isna().sum()

Area          0
Item          0
Element       0
Unit          0
2000       3188
2001       4727
2002       4628
2003       4607
2004       4602
2005       4334
2006       4292
2007       4450
2008       4469
2009       4482
2010       4051
2011       4629
2012       4151
2013       4264
2014       4386
2015       4476
2016       4513
2017       4689
2018       4741
2019       4777
2020       5094
dtype: int64

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58765 entries, 0 to 58764
Data columns (total 25 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Area     58765 non-null  object
 1   Item     58765 non-null  object
 2   Element  58765 non-null  object
 3   Unit     58765 non-null  object
 4   2000     55577 non-null  float64
 5   2001     54038 non-null  float64
 6   2002     54137 non-null  float64
 7   2003     54158 non-null  float64
 8   2004     54163 non-null  float64
 9   2005     54431 non-null  float64
 10  2006     54473 non-null  float64
 11  2007     54315 non-null  float64
 12  2008     54296 non-null  float64
 13  2009     54283 non-null  float64
 14  2010     54714 non-null  float64
 15  2011     54136 non-null  float64
 16  2012     54614 non-null  float64
 17  2013     54501 non-null  float64
 18  2014     54379 non-null  float64
 19  2015     54289 non-null  float64
 20  2016     54252 non-null  float64
 21  2017     54076 non-null  float64
 22  2018     54024 non-null  float64
 23  2019     53988 non-null  float64
 24  2020     53671 non-null  float64
dtypes: float64(21), object(4)
memory usage: 11.2+ MB

In [72]:
a = df["2000"].mean()
a

38561.26395415361

In [73]:
df["2000"] = df["2000"].fillna(a)

In [74]:
b = df["2001"].mean()

In [75]:
df["2001"] = df["2001"].fillna(b)

In [76]:
c = df["2002"].mean()

In [77]:
df["2002"] = df["2002"].fillna(c)

In [78]:
def mean(col):
    b = df[col].mean()
    df[col] = df[col].fillna(b)
mean("2003")
mean("2004")
mean("2005")
mean("2006")
mean("2007")
mean("2008")
mean("2009")
mean("2010")
mean("2011")
mean("2012")
mean("2013")
mean("2014")
mean("2015")
mean("2016")
mean("2017")
mean("2018")
mean("2019")
mean("2020")

In [79]:
row_sums = []
for i in range(len(df)):
    row_sum = sum(df.iloc[i, 5:]) # Assumes the first column is an index and should be excluded
    row_sums.append(row_sum)
row_sums
df["row_sums"] = row_sums
df

,Area,Item,Element,Unit,2000,2001,2002,2003,2004,2005,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,row_sums
0,Afghanistan,Crop Residues,Direct emissions (N2O),kilotonnes,5.200000e-01,5.267000e-01,8.200000e-01,9.988000e-01,8.225000e-01,1.182100e+00,...,1.372600e+00,1.401800e+00,1.458400e+00,1.242400e+00,1.194000e+00,1.061700e+00,8.988000e-01,1.217600e+00,1.317000e+00,2.236990e+01
1,Afghanistan,Crop Residues,Indirect emissions (N2O),kilotonnes,1.170000e-01,1.185000e-01,1.845000e-01,2.247000e-01,1.851000e-01,2.660000e-01,...,3.088000e-01,3.154000e-01,3.281000e-01,2.795000e-01,2.687000e-01,2.389000e-01,2.022000e-01,2.740000e-01,2.963000e-01,5.033200e+00
2,Afghanistan,Crop Residues,Emissions (N2O),kilotonnes,6.370000e-01,6.452000e-01,1.004500e+00,1.223500e+00,1.007500e+00,1.448100e+00,...,1.681500e+00,1.717300e+00,1.786500e+00,1.522000e+00,1.462700e+00,1.300500e+00,1.101100e+00,1.491600e+00,1.613300e+00,2.740320e+01
3,Afghanistan,Crop Residues,Emissions (CO2eq) from N2O (AR5),kilotonnes,1.688070e+02,1.709884e+02,2.661975e+02,3.242195e+02,2.669995e+02,3.837498e+02,...,4.455958e+02,4.550727e+02,4.734174e+02,4.033181e+02,3.876130e+02,3.446447e+02,2.917838e+02,3.952689e+02,4.275284e+02,7.261841e+03
4,Afghanistan,Crop Residues,Emissions (CO2eq) (AR5),kilotonnes,1.688070e+02,1.709884e+02,2.661975e+02,3.242195e+02,2.669995e+02,3.837498e+02,...,4.455958e+02,4.550727e+02,4.734174e+02,4.033181e+02,3.876130e+02,3.446447e+02,2.917838e+02,3.952689e+02,4.275284e+02,7.261841e+03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58760,OECD,All sectors without LULUCF,Emissions (CO2),kilotonnes,1.334328e+07,1.326305e+07,1.332979e+07,1.352237e+07,1.366651e+07,1.369481e+07,...,1.270146e+07,1.274243e+07,1.261664e+07,1.253301e+07,1.241227e+07,1.243658e+07,1.254684e+07,1.217070e+07,1.088919e+07,2.583541e+08
58761,OECD,All sectors without LULUCF,Emissions (CO2eq) from F-gases (AR5),kilotonnes,3.941893e+05,3.882647e+05,4.176531e+05,4.392191e+05,4.672796e+05,5.080909e+05,...,7.826597e+05,8.006688e+05,8.326775e+05,8.546258e+05,8.741566e+05,8.884415e+05,9.049044e+05,9.172806e+05,9.208261e+05,1.398276e+07
58762,OECD,All sectors without LULUCF,Emissions (CO2eq) from CH4 (AR5),kilotonnes,2.145052e+06,2.126567e+06,2.093083e+06,2.038232e+06,2.047953e+06,2.008645e+06,...,1.971959e+06,1.922551e+06,1.934854e+06,1.924370e+06,1.880327e+06,1.915982e+06,1.923635e+06,1.882769e+06,1.825476e+06,3.946588e+07
58763,OECD,All sectors without LULUCF,Emissions (CO2eq) from N2O (AR5),kilotonnes,8.535273e+05,8.496131e+05,8.400758e+05,8.124412e+05,8.328157e+05,8.123489e+05,...,8.490201e+05,8.204159e+05,8.325680e+05,8.289014e+05,8.218071e+05,8.400423e+05,8.349622e+05,8.118189e+05,8.009744e+05,1.644229e+07
58764,OECD,All sectors without LULUCF,Emissions (CO2eq) (AR5),kilotonnes,1.673605e+07,1.662750e+07,1.668060e+07,1.681226e+07,1.701456e+07,1.702390e+07,...,1.630510e+07,1.628606e+07,1.621674e+07,1.614090e+07,1.598856e+07,1.608104e+07,1.621034e+07,1.578256e+07,1.443647e+07,3.282450e+08

In [80]:
df.isna().sum()

Area        0
Item        0
Element     0
Unit        0
2000        0
2001        0
2002        0
2003        0
2004        0
2005        0
2006        0
2007        0
2008        0
2009        0
2010        0
2011        0
2012        0
2013        0
2014        0
2015        0
2016        0
2017        0
2018        0
2019        0
2020        0
row_sums    0
dtype: int64

In [81]:
total = df.groupby ('Area')["row_sums"].sum().sort_values(ascending = False)
total1=total.reset_index()

In [82]:
display(total)

Area
World                             8.496139e+09
Non-Annex I countries             5.689944e+09
Asia                              3.728696e+09
Annex I countries                 2.664934e+09
OECD                              2.479882e+09
                                      ...
Holy See                          7.491614e+02
Tokelau                           1.863293e+02
Norfolk Island                    8.144000e+00
Pitcairn                          0.000000e+00
Svalbard and Jan Mayen Islands    0.000000e+00
Name: row_sums, Length: 280, dtype: float64

In [83]:
total1.to_csv("question 1.csv",index=False)

In [84]:
df.to_csv("df.csv",index=False)

In [85]:
df.shape[1]

26